import express, {
  type ErrorRequestHandler,
  type Request,
  type Response,
} from "express";
import { randomUUID } from "crypto";
import helmet from "helmet";
import { rateLimit } from "express-rate-limit";
import swaggerUi from "swagger-ui-express";
import pinoHttp from "pino-http";
import logger from "./lib/logger";
import * as pollers from "./lib/pollers";
import { byUidOrIp, byIp } from "./lib/rateLimitKeys";
import { closeClient, ping as pingDb } from "./lib/db";
import verifyToken from "./lib/authMiddleware";
import langMiddleware from "./lib/langMiddleware";
import responseHelper from "./lib/responseHelper";
import { ensureIndexes, seedIfEmpty } from "./features/ad/ad.data";
import { ensureScheduleIndexes } from "./features/bus/schedule-db";
import { ensureIndexes as ensureBuildingIndexes } from "./features/building/building.data";
import "./features/building/building.sync"; // poller registration (side-effect)
import "./features/notices/notices.dispatch.poller"; // poller registration (side-effect, env-gated)
import * as busCache from "./lib/busCache";
import config from "./lib/config";

// Optional swagger JSON load — file is generated by `npm run swagger` and may
// not be present at build time. Use require + try/catch (not static import) so
// TS compilation doesn't fail on missing file.
let swaggerFile: object | undefined;
try {
  swaggerFile = require("./swagger/swagger-output.json");
} catch {
  logger.warn("swagger-output.json not found. Run 'npm run swagger' to generate it.");
}

const app = express();
app.set("trust proxy", 1);
app.use(helmet());
app.use(pinoHttp({
  logger,
  genReqId: (req, res) => {
    const existing = req.headers["x-request-id"];
    if (existing) return existing as string;
    const id = randomUUID();
    res.setHeader("X-Request-Id", id);
    return id;
  },
  customProps: (req) => ({
    appVersion: req.headers["x-app-version"] || null,
    platform: req.headers["x-platform"] || null,
  }),
}));
app.use(express.json({ limit: "100kb" }));
app.use(langMiddleware);
app.use(responseHelper);

// Swagger API docs (non-production only)
if (swaggerFile && !config.isProduction) {
  app.use("/api-docs", swaggerUi.serve, swaggerUi.setup(swaggerFile, { explorer: true }));
}

// Health check (unprotected, before auth/rate-limiting)
app.get("/health", (_req, res) => {
  res.status(200).json({ status: "ok", uptime: process.uptime() });
});

// Readiness probe: DB connectivity + (pollers running OR api-only role)
app.get("/health/ready", async (_req, res) => {
  try {
    await pingDb();
    const role = process.env.ROLE || "combined";
    const pollersReady = role === "api" ? true : pollers.isReady();
    if (!pollersReady) {
      return res.status(503).json({ status: "unavailable", reason: "pollers not started" });
    }
    res.status(200).json({ status: "ready", uptime: process.uptime() });
  } catch (_err) {
    res.status(503).json({ status: "unavailable", reason: "db unreachable" });
  }
});

// Rate limiters (uid-based to handle shared campus WiFi)
const searchLimiter = rateLimit({
  windowMs: 60 * 1000,
  max: 60,
  keyGenerator: byUidOrIp,
  standardHeaders: true,
  legacyHeaders: false,
  message: { error: { code: "RATE_LIMIT", message: "Too many requests" } },
});

const generalLimiter = rateLimit({
  windowMs: 60 * 1000,
  max: 120,
  keyGenerator: byIp,
  standardHeaders: true,
  legacyHeaders: false,
  message: { error: { code: "RATE_LIMIT", message: "Too many requests" } },
});

// Feature routes
import searchRoute from "./features/search/search.routes";
import realtimeRoutes from "./features/bus/realtime.routes";
import campusEtaRoutes from "./features/bus/campus-eta.routes";
import scheduleRoutes from "./features/bus/schedule.routes";
import busConfigRoutes from "./features/bus/bus-config.routes";
import routeOverlayRoutes from "./features/bus/route-overlay.routes";
import stationRoute from "./features/station/station.routes";
import uiRoute from "./features/ui/ui.routes";
import adRoute from "./features/ad/ad.routes";
import appRoute from "./features/app/app.routes";
import mapConfigRoutes from "./features/map/map-config.routes";
import mapMarkersRoutes from "./features/map/map-markers.routes";
import mapOverlaysRoutes from "./features/map/map-overlays.routes";
import buildingRoutes from "./features/building/building.routes";
import noticesRoute from "./features/notices/notices.routes";
import noticesInternalRoute from "./features/notices/notices.internal.routes";
import { ensureNoticeIndexes } from "./features/notices/notices.data";

const noticesLimiter = rateLimit({
  windowMs: 60 * 1000,
  max: 120,
  keyGenerator: byUidOrIp,
  standardHeaders: true,
  legacyHeaders: false,
  message: { error: { code: "RATE_LIMIT", message: "Too many requests" } },
});

app.use("/search", verifyToken, searchLimiter, searchRoute);
app.use("/bus/realtime", generalLimiter, realtimeRoutes);
app.use("/bus/station", generalLimiter, stationRoute);
app.use("/bus/campus", generalLimiter, campusEtaRoutes);
app.use("/bus/schedule", generalLimiter, scheduleRoutes);
app.use("/bus/config", generalLimiter, busConfigRoutes);
app.use("/bus/route", generalLimiter, routeOverlayRoutes);
app.use("/ui", generalLimiter, uiRoute);
app.use("/ad", verifyToken, adRoute);
app.use("/app", generalLimiter, appRoute);
app.use("/map/config", generalLimiter, mapConfigRoutes);
app.use("/map/markers", generalLimiter, mapMarkersRoutes);
app.use("/map/overlays", generalLimiter, mapOverlaysRoutes);
app.use("/building", generalLimiter, buildingRoutes);
app.use("/notices", verifyToken, noticesLimiter, noticesRoute);
// Internal-only — auth via shared X-Internal-Token header inside the route.
// Skips Firebase verifyToken (caller is the crawler service, not an end user)
// and the noticesLimiter (single ping per crawl cycle).
app.use("/internal/notices", noticesInternalRoute);

// 404 handler (after all routes, before error handler)
app.use((req: Request, res: Response) => {
  res.error(404, "NOT_FOUND", `${req.method} ${req.path} not found`);
});

// Shared error handler (4-arg form — _next required for Express to recognize
// this as error middleware even when unused).
const errorHandler: ErrorRequestHandler = (err, _req, res, _next) => {
  logger.error({ err }, "Unhandled request error");
  res.status(500).json({ error: { code: "INTERNAL_ERROR", message: "Internal server error" } });
};
app.use(errorHandler);

// Start server
if (require.main === module) {
  (async () => {
    // Verify MongoDB connectivity (non-fatal: bus/station/search work without DB)
    try {
      await pingDb();
      logger.info("[db] MongoDB connected");
    } catch (err) {
      logger.warn({ err: (err as { message?: string }).message }, "[db] MongoDB connection failed");
    }

    // Initialize ad system (non-fatal: warn and continue on failure)
    try {
      await ensureIndexes();
      await seedIfEmpty();
    } catch (err) {
      logger.warn({ err: (err as { message?: string }).message }, "[ad] Startup initialization failed");
    }

    // Ensure bus_cache TTL index exists (non-fatal)
    try {
      await busCache.ensureIndex();
      logger.info("[bus_cache] TTL index ensured");
    } catch (err) {
      logger.warn({ err: (err as { message?: string }).message }, "[bus_cache] Index setup failed");
    }

    // Ensure schedule indexes (non-fatal)
    try {
      await ensureScheduleIndexes();
      logger.info("[schedule] Indexes ensured");
    } catch (err) {
      logger.warn({ err: (err as { message?: string }).message }, "[schedule] Index setup failed");
    }

    // Ensure building indexes (non-fatal)
    try {
      await ensureBuildingIndexes();
      logger.info("[building] Indexes ensured");
    } catch (err) {
      logger.warn({ err: (err as { message?: string }).message }, "[building] Index setup failed");
    }

    // Ensure notice indexes (non-fatal but logged at error level on final
    // failure — without this index, list queries fall back to full collection
    // scan, which is expensive for the 54MB+ notices collection).
    try {
      let lastErr: unknown = null;
      for (let attempt = 1; attempt <= 3; attempt++) {
        try {
          await ensureNoticeIndexes();
          logger.info({ attempt }, "[notices] Indexes ensured");
          lastErr = null;
          break;
        } catch (err) {
          lastErr = err;
          if (attempt < 3) await new Promise((r) => setTimeout(r, 1000 * attempt));
        }
      }
      if (lastErr) {
        logger.error(
          { err: (lastErr as { message?: string }).message },
          "[notices] Index setup failed after 3 attempts — list queries will full-scan",
        );
      }
    } catch (err) {
      logger.error({ err: (err as { message?: string }).message }, "[notices] Index setup crashed");
    }

    // ROLE=poller: run pollers only, no HTTP server
    // ROLE=api: run HTTP server only, no pollers (reads from bus_cache written by poller service)
    // ROLE=combined (default): run both — single-container backward-compatible mode
    const role = process.env.ROLE || "combined";

    if (role === "poller") {
      logger.info({ role }, "Running in poller-only mode");
      pollers.startAll();
      const shutdown = async () => {
        logger.info("Shutting down poller...");
        pollers.stopAll();
        await closeClient();
        process.exit(0);
      };
      process.on("SIGTERM", shutdown);
      process.on("SIGINT", shutdown);
      return;
    }

    if (role === "combined") {
      pollers.startAll();
    }

    const server = app.listen(config.port, () => {
      logger.info({
        mode: config.getModeLabel(),
        port: config.port,
        db: config.mongo.dbName,
        adDb: config.ad.dbName,
        buildingDb: config.building.dbName,
        noticesDb: config.notices.dbName,
        api: config.useProdApi ? "PROD" : "DEV",
        role,
      }, "Server started");
    });

    // Graceful shutdown (5s timeout to avoid hanging before Docker SIGKILL)
    let shuttingDown = false;
    const shutdown = async () => {
      if (shuttingDown) return;
      shuttingDown = true;
      logger.info("Shutting down...");
      const forceExit = setTimeout(() => {
        logger.error("Shutdown timed out, forcing exit");
        process.exit(1);
      }, 5000);
      forceExit.unref();
      server.close();
      pollers.stopAll();
      await closeClient();
      process.exit(0);
    };
    process.on("SIGTERM", shutdown);
    process.on("SIGINT", shutdown);
  })();
}

export = app;
