import { Router } from "express";
import { getMapConfig } from "./map-config.data";
import type { SupportedLang } from "../../lib/types";

const router = Router();

/**
 * GET /map/config
 * Returns campus definitions and map layer registry.
 * Text is localised based on Accept-Language (req.lang).
 * ETag is auto-generated by Express; Vary header set by langMiddleware.
 */
router.get("/", (req, res) => {
  const config = getMapConfig(req.lang as SupportedLang);
  res.success(config);
});

export = router;
