const { Router } = require("express");
const { getMapConfig } = require("./map-config.data");

const router = Router();

/**
 * GET /map/config
 * Returns campus definitions and map layer registry.
 * Text is localised based on Accept-Language (req.lang).
 * ETag is auto-generated by Express; Vary header set by langMiddleware.
 */
router.get("/", (req, res) => {
  const config = getMapConfig(req.lang);
  res.success(config);
});

module.exports = router;
