import type { JongroStation, JongroStationMapping } from "./types";

const Jongro02Stations: JongroStation[] = [
  { sequence: "1", stationName: "성균관대학교", stationNumber: "01881", eta: "도착 정보 없음", isFirstStation: true, isLastStation: false, isRotationStation: false, busType: "BusType.jonro02Bus", transferLines: [] },
  { sequence: "2", stationName: "서울성곽.성대후문", stationNumber: "01515", eta: "도착 정보 없음", isFirstStation: false, isLastStation: false, isRotationStation: false, busType: "BusType.jonro02Bus", transferLines: [] },
  { sequence: "3", stationName: "통일부", stationNumber: "01525", eta: "도착 정보 없음", isFirstStation: false, isLastStation: false, isRotationStation: false, busType: "BusType.jonro02Bus", transferLines: [] },
  { sequence: "4", stationName: "감사원", stationNumber: "01536", eta: "도착 정보 없음", isFirstStation: false, isLastStation: false, isRotationStation: false, busType: "BusType.jonro02Bus", transferLines: [] },
  { sequence: "5", stationName: "사우디대사관앞.경남빌라", stationNumber: "01547", eta: "도착 정보 없음", isFirstStation: false, isLastStation: false, isRotationStation: false, busType: "BusType.jonro02Bus", transferLines: [] },
  { sequence: "6", stationName: "안국선원.삼거리", stationNumber: "01548", eta: "도착 정보 없음", isFirstStation: false, isLastStation: false, isRotationStation: false, busType: "BusType.jonro02Bus", transferLines: [] },
  { sequence: "7", stationName: "북촌한옥마을입구.정세권활동터", stationNumber: "01556", eta: "도착 정보 없음", isFirstStation: false, isLastStation: false, isRotationStation: false, busType: "BusType.jonro02Bus", transferLines: [] },
  { sequence: "8", stationName: "가회동주민센터", stationNumber: "01564", eta: "도착 정보 없음", isFirstStation: false, isLastStation: false, isRotationStation: false, busType: "BusType.jonro02Bus", transferLines: [] },
  { sequence: "9", stationName: "아름다운가게.정독도서관", stationNumber: "01570", eta: "도착 정보 없음", isFirstStation: false, isLastStation: false, isRotationStation: false, busType: "BusType.jonro02Bus", transferLines: [] },
  { sequence: "10", stationName: "헌법재판소.안국역", stationNumber: "01576", eta: "도착 정보 없음", isFirstStation: false, isLastStation: false, isRotationStation: false, busType: "BusType.jonro02Bus", transferLines: [{ line: "3", color: "EF7C1C" }] },
  { sequence: "11", stationName: "수운회관", stationNumber: "01583", eta: "도착 정보 없음", isFirstStation: false, isLastStation: false, isRotationStation: false, busType: "BusType.jonro02Bus", transferLines: [{ line: "3", color: "EF7C1C" }] },
  { sequence: "12", stationName: "낙원상가", stationNumber: "01589", eta: "도착 정보 없음", isFirstStation: false, isLastStation: false, isRotationStation: false, busType: "BusType.jonro02Bus", transferLines: [{ line: "1", color: "0052A4" }, { line: "3", color: "EF7C1C" }, { line: "5", color: "996CAC" }] },
  { sequence: "13", stationName: "금강제화", stationNumber: "01596", eta: "도착 정보 없음", isFirstStation: false, isLastStation: false, isRotationStation: true, busType: "BusType.jonro02Bus", transferLines: [] },
  { sequence: "14", stationName: "종각역YMCA", stationNumber: "01683", eta: "도착 정보 없음", isFirstStation: false, isLastStation: false, isRotationStation: false, busType: "BusType.jonro02Bus", transferLines: [] },
  { sequence: "15", stationName: "종각.공평유적전시관", stationNumber: "01888", eta: "도착 정보 없음", isFirstStation: false, isLastStation: false, isRotationStation: false, busType: "BusType.jonro02Bus", transferLines: [{ line: "1", color: "0052A4" }] },
  { sequence: "16", stationName: "조계사", stationNumber: "01889", eta: "도착 정보 없음", isFirstStation: false, isLastStation: false, isRotationStation: false, busType: "BusType.jonro02Bus", transferLines: [] },
  { sequence: "17", stationName: "안국역.인사동", stationNumber: "01200", eta: "도착 정보 없음", isFirstStation: false, isLastStation: false, isRotationStation: false, busType: "BusType.jonro02Bus", transferLines: [{ line: "3", color: "EF7C1C" }] },
  { sequence: "18", stationName: "안국역2번출구앞", stationNumber: "01805", eta: "도착 정보 없음", isFirstStation: false, isLastStation: false, isRotationStation: false, busType: "BusType.jonro02Bus", transferLines: [{ line: "3", color: "EF7C1C" }] },
  { sequence: "19", stationName: "재동초등학교", stationNumber: "01812", eta: "도착 정보 없음", isFirstStation: false, isLastStation: false, isRotationStation: false, busType: "BusType.jonro02Bus", transferLines: [] },
  { sequence: "20", stationName: "가회동주민센터", stationNumber: "01826", eta: "도착 정보 없음", isFirstStation: false, isLastStation: false, isRotationStation: false, busType: "BusType.jonro02Bus", transferLines: [] },
  { sequence: "21", stationName: "북촌한옥마을입구.정세권활동터", stationNumber: "01833", eta: "도착 정보 없음", isFirstStation: false, isLastStation: false, isRotationStation: false, busType: "BusType.jonro02Bus", transferLines: [] },
  { sequence: "22", stationName: "안국선원.삼거리", stationNumber: "01839", eta: "도착 정보 없음", isFirstStation: false, isLastStation: false, isRotationStation: false, busType: "BusType.jonro02Bus", transferLines: [] },
  { sequence: "23", stationName: "사우디대사관", stationNumber: "01845", eta: "도착 정보 없음", isFirstStation: false, isLastStation: false, isRotationStation: false, busType: "BusType.jonro02Bus", transferLines: [] },
  { sequence: "24", stationName: "감사원", stationNumber: "01851", eta: "도착 정보 없음", isFirstStation: false, isLastStation: false, isRotationStation: false, busType: "BusType.jonro02Bus", transferLines: [] },
  { sequence: "25", stationName: "통일부", stationNumber: "01856", eta: "도착 정보 없음", isFirstStation: false, isLastStation: false, isRotationStation: false, busType: "BusType.jonro02Bus", transferLines: [] },
  { sequence: "26", stationName: "성대후문.와룡공원", stationNumber: "01860", eta: "도착 정보 없음", isFirstStation: false, isLastStation: true, isRotationStation: false, busType: "BusType.jonro02Bus", transferLines: [] },
];

const Jongro07Stations: JongroStation[] = [
  { sequence: "1", stationName: "명륜새마을금고", stationNumber: "01504", eta: "도착 정보 없음", isFirstStation: true, isLastStation: false, isRotationStation: false, busType: "BusType.jonro07Bus", transferLines: [] },
  { sequence: "2", stationName: "서울국제고등학교", stationNumber: "01512", eta: "도착 정보 없음", isFirstStation: false, isLastStation: false, isRotationStation: false, busType: "BusType.jonro07Bus", transferLines: [] },
  { sequence: "3", stationName: "국민생활관", stationNumber: "01521", eta: "도착 정보 없음", isFirstStation: false, isLastStation: false, isRotationStation: false, busType: "BusType.jonro07Bus", transferLines: [] },
  { sequence: "4", stationName: "혜화초등학교", stationNumber: "01532", eta: "도착 정보 없음", isFirstStation: false, isLastStation: false, isRotationStation: false, busType: "BusType.jonro07Bus", transferLines: [] },
  { sequence: "5", stationName: "혜화우체국", stationNumber: "01543", eta: "도착 정보 없음", isFirstStation: false, isLastStation: false, isRotationStation: false, busType: "BusType.jonro07Bus", transferLines: [] },
  { sequence: "6", stationName: "혜화역4번출구", stationNumber: "01876", eta: "도착 정보 없음", isFirstStation: false, isLastStation: false, isRotationStation: false, busType: "BusType.jonro07Bus", transferLines: [{ line: "4", color: "00A5DE" }] },
  { sequence: "7", stationName: "혜화역.서울대병원입구", stationNumber: "01221", eta: "도착 정보 없음", isFirstStation: false, isLastStation: false, isRotationStation: false, busType: "BusType.jonro07Bus", transferLines: [] },
  { sequence: "8", stationName: "방송통신대앞", stationNumber: "01877", eta: "도착 정보 없음", isFirstStation: false, isLastStation: false, isRotationStation: true, busType: "BusType.jonro07Bus", transferLines: [] },
  { sequence: "9", stationName: "이화사거리", stationNumber: "01886", eta: "도착 정보 없음", isFirstStation: false, isLastStation: false, isRotationStation: false, busType: "BusType.jonro07Bus", transferLines: [] },
  { sequence: "10", stationName: "방송통신대.이화장", stationNumber: "01219", eta: "도착 정보 없음", isFirstStation: false, isLastStation: false, isRotationStation: false, busType: "BusType.jonro07Bus", transferLines: [] },
  { sequence: "11", stationName: "혜화역.마로니에공원", stationNumber: "01220", eta: "도착 정보 없음", isFirstStation: false, isLastStation: false, isRotationStation: false, busType: "BusType.jonro07Bus", transferLines: [{ line: "4", color: "00A5DE" }] },
  { sequence: "12", stationName: "혜화역1번출구", stationNumber: "01592", eta: "도착 정보 없음", isFirstStation: false, isLastStation: false, isRotationStation: false, busType: "BusType.jonro07Bus", transferLines: [{ line: "4", color: "00A5DE" }] },
  { sequence: "13", stationName: "혜화동로터리", stationNumber: "01226", eta: "도착 정보 없음", isFirstStation: false, isLastStation: false, isRotationStation: false, busType: "BusType.jonro07Bus", transferLines: [] },
  { sequence: "14", stationName: "성대입구", stationNumber: "01697", eta: "도착 정보 없음", isFirstStation: false, isLastStation: false, isRotationStation: false, busType: "BusType.jonro07Bus", transferLines: [] },
  { sequence: "15", stationName: "성균관대정문", stationNumber: "01615", eta: "도착 정보 없음", isFirstStation: false, isLastStation: false, isRotationStation: false, busType: "BusType.jonro07Bus", transferLines: [] },
  { sequence: "16", stationName: "600주년기념관", stationNumber: "01616", eta: "도착 정보 없음", isFirstStation: false, isLastStation: false, isRotationStation: false, busType: "BusType.jonro07Bus", transferLines: [] },
  { sequence: "17", stationName: "성균관대운동장", stationNumber: "01617", eta: "도착 정보 없음", isFirstStation: false, isLastStation: false, isRotationStation: false, busType: "BusType.jonro07Bus", transferLines: [] },
  { sequence: "18", stationName: "학생회관", stationNumber: "01618", eta: "도착 정보 없음", isFirstStation: false, isLastStation: false, isRotationStation: false, busType: "BusType.jonro07Bus", transferLines: [] },
  { sequence: "19", stationName: "성균관대학교", stationNumber: "01722", eta: "도착 정보 없음", isFirstStation: false, isLastStation: true, isRotationStation: false, busType: "BusType.jonro07Bus", transferLines: [] },
];

// TOPIS lastStnId → station sequence + name. Keys are numeric in source but
// JS coerces to string at access time; fetcher uses string lookups.
const Jongro02stationMapping: JongroStationMapping = {
  100900204: { sequence: 1, stationName: "성균관대학교" },
  100900202: { sequence: 2, stationName: "서울성곽.성대후문" },
  100900045: { sequence: 3, stationName: "통일부" },
  100900069: { sequence: 4, stationName: "감사원" },
  100900059: { sequence: 5, stationName: "사우디대사관앞.경남빌라" },
  100900058: { sequence: 6, stationName: "안국선원.삼거리" },
  100900052: { sequence: 7, stationName: "북촌한옥마을입구.정세권활동터" },
  100900048: { sequence: 8, stationName: "가회동주민센터" },
  100900092: { sequence: 9, stationName: "아름다운가게.정독도서관" },
  100900086: { sequence: 10, stationName: "헌법재판소.안국역" },
  100900081: { sequence: 11, stationName: "수운회관" },
  100900078: { sequence: 12, stationName: "낙원상가" },
  100900121: { sequence: 13, stationName: "금강제화" },
  100900116: { sequence: 14, stationName: "종각역YMCA" },
  100900211: { sequence: 15, stationName: "종각.공평유적전시관" },
  100900213: { sequence: 16, stationName: "조계사" },
  100000104: { sequence: 17, stationName: "안국역.인사동" },
  100900189: { sequence: 18, stationName: "안국역2번출구앞" },
  100900131: { sequence: 19, stationName: "재동초등학교" },
  100900168: { sequence: 20, stationName: "가회동주민센터" },
  100900162: { sequence: 21, stationName: "북촌한옥마을입구.정세권활동터" },
  100900157: { sequence: 22, stationName: "안국선원.삼거리" },
  100900153: { sequence: 23, stationName: "사우디대사관" },
  100900147: { sequence: 24, stationName: "감사원" },
  100900172: { sequence: 25, stationName: "통일부" },
  100900203: { sequence: 26, stationName: "성대후문.와룡공원" },
};

const Jongro07stationMapping: JongroStationMapping = {
  100900197: { sequence: 1, stationName: "명륜새마을금고" },
  100900031: { sequence: 2, stationName: "서울국제고등학교" },
  100900017: { sequence: 3, stationName: "국민생활관" },
  100900003: { sequence: 4, stationName: "혜화초등학교" },
  100900063: { sequence: 5, stationName: "혜화우체국" },
  100900027: { sequence: 6, stationName: "혜화역4번출구" },
  100000125: { sequence: 7, stationName: "혜화역.서울대병원입구" },
  100900028: { sequence: 8, stationName: "방송통신대앞" },
  100900043: { sequence: 9, stationName: "이화사거리" },
  100000123: { sequence: 10, stationName: "방송통신대.이화장" },
  100000124: { sequence: 11, stationName: "혜화역.마로니에공원" },
  100900075: { sequence: 12, stationName: "혜화역1번출구" },
  100000130: { sequence: 13, stationName: "혜화동로터리" },
  100900199: { sequence: 14, stationName: "성대입구" },
  100900218: { sequence: 15, stationName: "성균관대정문" },
  100900219: { sequence: 16, stationName: "600주년기념관" },
  100900220: { sequence: 17, stationName: "성균관대운동장" },
  100900221: { sequence: 18, stationName: "학생회관" },
  100900110: { sequence: 19, stationName: "성균관대학교" },
};

export {
  Jongro02Stations,
  Jongro07Stations,
  Jongro02stationMapping,
  Jongro07stationMapping,
};
