import { Controller, Get, Req } from "@nestjs/common";
import type { Request } from "express";
import type { SupportedLang } from "../../infra/types";
import { MapService } from "../map.service";

/**
 * Port of the /map/config route (mounted at /map/config, no auth,
 * generalLimiter). Returns the config object; the global ResponseInterceptor
 * wraps it in the {meta:{lang},data} envelope, matching the Express route's
 * res.success(config). Vary header is set by LangMiddleware, ETag
 * auto-generated by Express (unchanged in Nest's Express adapter).
 *
 * Async since the event marker layers joined the list: they are present only
 * while an activation window is open, which is a Mongo read. That read is
 * contained inside map-config.data — a failure there serves the base layers
 * rather than propagating, so this route keeps the never-fails property it had
 * when it was sync.
 */
@Controller("map/config")
export class MapConfigController {
  constructor(private readonly map: MapService) {}

  // GET /map/config
  @Get()
  getConfig(@Req() req: Request): ReturnType<MapService["getMapConfig"]> {
    return this.map.getMapConfig(req.lang as SupportedLang);
  }
}
