import { Controller, Get, Req } from "@nestjs/common";
import type { Request } from "express";
import type { SupportedLang } from "../../../lib/types";
import { MapService } from "../map.service";

/**
 * Port of features/map/map-config.routes.ts (mounted at /map/config, no auth,
 * generalLimiter). Sync handler — returns the config object; the global
 * ResponseInterceptor wraps it in the {meta:{lang},data} envelope, matching the
 * Express route's res.success(config). Vary header is set by LangMiddleware,
 * ETag auto-generated by Express (unchanged in Nest's Express adapter).
 */
@Controller("map/config")
export class MapConfigController {
  constructor(private readonly map: MapService) {}

  // GET /map/config
  @Get()
  getConfig(@Req() req: Request): ReturnType<MapService["getMapConfig"]> {
    return this.map.getMapConfig(req.lang as SupportedLang);
  }
}
